export const GET_PRODUCTS = "PRODUCTS/GET_PRODUCTS";
export const GET_PRODUCT = "PRODUCTS/GET_PRODUCT";
export const CREATE_PRODUCT = "PRODUCTS/CREATE_PRODUCT";
export const EDIT_PRODUCT = "PRODUCTS/EDIT_PRODUCT";
export const DELETE_PRODUCT = "PRODUCTS/DELETE_PRODUCT";