export const GET_PRODUCTS = "PRODUCTS/GET_PRODUCTS";
export const GET_PRODUCT = "PRODUCTS/GET_PRODUCT";
export const CREATE_PRODUCT = "PRODUCTS/CREATE_PRODUCT";
export const EDIT_PRODUCT = "PRODUCTS/EDIT_PRODUCT";
export const DELETE_PRODUCT = "PRODUCTS/DELETE_PRODUCT";

export const GET_SHOPPING_CART_PRODUCTS = "SHOPPING/GET_SHOPPING_CART_PRODUCTS";
export const GET_SHOPPING_CART_PRODUCT = "SHOPPING/GET_SHOPPING_CART_PRODUCT";
export const CREATE_SHOPPING_CART_PRODUCT = "SHOPPING/CREATE_SHOPPING_CART_PRODUCT";
export const EDIT_SHOPPING_CART_PRODUCT = "SHOPPING/EDIT_SHOPPING_CART_PRODUCT";
export const DELETE_SHOPPING_CART_PRODUCT = "SHOPPING/DELETE_SHOPPING_CART_PRODUCT";